language: java
dist: trusty
sudo: false
jdk:
  - oraclejdk8
before_install:
- chmod +x mvnw
services:
    - postgresql
before_script:
    - psql -c 'CREATE DATABASE testdb1;' -U postgres;
    - psql -c "ALTER USER postgres WITH PASSWORD 'ifes'" -d template1;
addons:
  sonarcloud:
    organization: "gerentefornecedor"
    token:
      secure: "$SONAR_KEY"
script:
  - mvn org.sonarsource.scanner.maven:sonar-maven-plugin:3.4.0.905:sonar
  #- sonar-scanner
   #- mvn clean install
   #- mvn sonar:sonar
deploy:
 provider: heroku
 api-key:
  secure: $HEROKU_KEY
 app: servicogerentefornecedor
